// Demo seed data for the SQLite-backed API. Ported from the old client-side
// src/data/*.ts mock files now that the database, not the browser, owns it.
import type {
  Claim,
  Dependent,
  Member,
  Payment,
  Plan,
  PortalDocument,
  PriorAuthorization,
  Provider,
} from '../src/types/domain.js';

/** Deterministic demo "now" so seeded relative dates don't reshuffle on every reseed. */
const DEMO_NOW = new Date('2026-09-05T16:00:00Z');

function daysAgo(days: number, hourOffset = 0): string {
  return new Date(DEMO_NOW.getTime() - days * 86400000 - hourOffset * 3600000).toISOString();
}

function daysFromNow(days: number): string {
  return new Date(DEMO_NOW.getTime() + days * 86400000).toISOString();
}

export const seedMember: Member = {
  id: 'mem_jordan_alvarez',
  name: 'Jordan Alvarez',
  memberNumber: 'CP-88213045',
  email: 'jordan.alvarez@example.com',
  phone: '(555) 214-7788',
  dateOfBirth: '1988-04-12',
  address: '412 Willowbrook Lane, Springfield, CO 80112',
  planId: 'plan_gold_ppo_2026',
};

export const seedDependents: Dependent[] = [
  {
    id: 'dep_rowan_alvarez',
    name: 'Rowan Alvarez',
    relationship: 'spouse',
    dateOfBirth: '1990-11-02',
    memberId: 'mem_jordan_alvarez',
  },
  {
    id: 'dep_mila_alvarez',
    name: 'Mila Alvarez',
    relationship: 'child',
    dateOfBirth: '2017-06-23',
    memberId: 'mem_jordan_alvarez',
  },
];

export const seedPlan: Plan = {
  id: 'plan_gold_ppo_2026',
  name: 'CarePath Gold PPO',
  type: 'PPO',
  tier: 'gold',
  groupNumber: 'GRP-48213',
  effectiveDate: '2026-01-01T00:00:00.000Z',
  renewalDate: '2027-01-01T00:00:00.000Z',
  premiumMonthly: 612,
  deductibleIndividual: 1500,
  deductibleFamily: 3000,
  deductibleMetIndividual: 950,
  deductibleMetFamily: 1800,
  outOfPocketMaxIndividual: 6000,
  outOfPocketMaxFamily: 12000,
  outOfPocketMetIndividual: 2100,
  outOfPocketMetFamily: 4200,
  planDocumentUrl: '#doc_plan_document',
  coverage: [
    { id: 'cov_primary_care', category: 'Doctor visits', serviceName: 'Primary care visit', costShare: '$25 copay', priorAuthRequired: false },
    { id: 'cov_specialist', category: 'Doctor visits', serviceName: 'Specialist visit', costShare: '$50 copay', priorAuthRequired: false },
    { id: 'cov_preventive', category: 'Doctor visits', serviceName: 'Preventive / annual exam', costShare: 'No charge', priorAuthRequired: false },
    { id: 'cov_urgent_care', category: 'Urgent & emergency', serviceName: 'Urgent care visit', costShare: '$75 copay', priorAuthRequired: false },
    { id: 'cov_er', category: 'Urgent & emergency', serviceName: 'Emergency room', costShare: '$350 copay after deductible', priorAuthRequired: false },
    { id: 'cov_generic_rx', category: 'Prescription drugs', serviceName: 'Generic drugs', costShare: '$15 copay', priorAuthRequired: false },
    { id: 'cov_brand_rx', category: 'Prescription drugs', serviceName: 'Preferred brand drugs', costShare: '$45 copay', priorAuthRequired: false },
    { id: 'cov_specialty_rx', category: 'Prescription drugs', serviceName: 'Specialty drugs', costShare: '20% coinsurance', priorAuthRequired: true },
    { id: 'cov_imaging', category: 'Tests & imaging', serviceName: 'Advanced imaging (MRI/CT)', costShare: '20% coinsurance after deductible', priorAuthRequired: true },
    { id: 'cov_pt', category: 'Rehabilitation', serviceName: 'Physical therapy (20 visits/yr)', costShare: '$40 copay per visit', priorAuthRequired: false },
    { id: 'cov_mental_health', category: 'Behavioral health', serviceName: 'Mental health outpatient visit', costShare: '$25 copay', priorAuthRequired: false },
    { id: 'cov_dme', category: 'Equipment', serviceName: 'Durable medical equipment', costShare: '20% coinsurance', priorAuthRequired: true },
  ],
};

export const seedProviders: Provider[] = [
  {
    id: 'prov_kapoor',
    name: 'Priya Kapoor',
    specialty: 'Family Medicine',
    credentials: 'MD',
    network: 'in_network',
    address: '210 Cedar Grove Blvd, Suite 100',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-2200',
    distanceMiles: 2.1,
    rating: 4.8,
    acceptingNewPatients: true,
    telehealth: true,
    languages: ['English', 'Hindi'],
    bio: 'Family medicine physician focused on preventive care and chronic condition management for the whole family.',
  },
  {
    id: 'prov_webb',
    name: 'Marcus Webb',
    specialty: 'Cardiology',
    credentials: 'MD',
    network: 'in_network',
    address: '88 Heartline Way, Suite 300',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-5510',
    distanceMiles: 4.6,
    rating: 4.6,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English'],
    bio: 'Cardiologist specializing in preventive cardiology and management of hypertension and arrhythmia.',
  },
  {
    id: 'prov_suarez',
    name: 'Elena Suarez',
    specialty: 'Pediatrics',
    credentials: 'MD',
    network: 'in_network',
    address: '55 Maple Court',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-6620',
    distanceMiles: 1.8,
    rating: 4.9,
    acceptingNewPatients: true,
    telehealth: true,
    languages: ['English', 'Spanish'],
    bio: 'Pediatrician providing well-child visits, vaccinations, and urgent pediatric care.',
  },
  {
    id: 'prov_kim',
    name: 'Grace Kim',
    specialty: 'Dermatology',
    credentials: 'MD',
    network: 'in_network',
    address: '19 Aspen Ridge Rd, Suite 210',
    city: 'Springfield',
    state: 'CO',
    zip: '80113',
    phone: '(555) 401-7743',
    distanceMiles: 6.2,
    rating: 4.4,
    acceptingNewPatients: false,
    telehealth: false,
    languages: ['English', 'Korean'],
    bio: 'Board-certified dermatologist treating skin conditions, screenings, and minor procedures.',
  },
  {
    id: 'prov_otieno',
    name: 'Samuel Otieno',
    specialty: 'Orthopedic Surgery',
    credentials: 'MD',
    network: 'in_network',
    address: '340 Trailhead Ave, Suite 500',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-9081',
    distanceMiles: 5.0,
    rating: 4.7,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English', 'Swahili'],
    bio: 'Orthopedic surgeon specializing in sports medicine and joint preservation.',
  },
  {
    id: 'prov_whitfield',
    name: 'Dana Whitfield',
    specialty: 'Physical Therapy',
    credentials: 'DPT',
    network: 'in_network',
    address: '12 Riverside Dr',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-3345',
    distanceMiles: 3.3,
    rating: 4.8,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English'],
    bio: 'Physical therapist specializing in post-surgical rehab and sports injury recovery.',
  },
  {
    id: 'prov_brooks',
    name: 'Alan Brooks',
    specialty: 'Psychiatry',
    credentials: 'MD',
    network: 'in_network',
    address: '77 Willowbrook Lane, Suite 4',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-1187',
    distanceMiles: 0.9,
    rating: 4.9,
    acceptingNewPatients: true,
    telehealth: true,
    languages: ['English'],
    bio: 'Psychiatrist offering medication management and therapy for anxiety, depression, and mood disorders.',
  },
  {
    id: 'prov_chen',
    name: 'Naomi Chen',
    specialty: 'OB-GYN',
    credentials: 'MD',
    network: 'in_network',
    address: '404 Sunrise Pkwy, Suite 220',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-6688',
    distanceMiles: 3.9,
    rating: 4.8,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English', 'Mandarin'],
    bio: "OB-GYN providing annual exams, prenatal care, and women's health services.",
  },
  {
    id: 'prov_alvarado',
    name: 'Victor Alvarado',
    specialty: 'Urgent Care',
    credentials: 'MD',
    network: 'in_network',
    address: '900 Quickcare Plaza',
    city: 'Springfield',
    state: 'CO',
    zip: '80112',
    phone: '(555) 401-0000',
    distanceMiles: 2.5,
    rating: 4.3,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English', 'Spanish'],
    bio: 'Urgent care physician for same-day illness and injury visits, open evenings and weekends.',
  },
  {
    id: 'prov_grant',
    name: 'Felicia Grant',
    specialty: 'Dermatology',
    credentials: 'MD',
    network: 'out_of_network',
    address: '1500 Uptown Ave, Suite 900',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    phone: '(555) 990-2244',
    distanceMiles: 28.4,
    rating: 4.5,
    acceptingNewPatients: true,
    telehealth: false,
    languages: ['English'],
    bio: 'Dermatologist offering cosmetic and medical dermatology services. Not contracted with CarePath plans.',
  },
];

export const seedClaims: Claim[] = [
  {
    id: 'clm_1',
    claimNumber: 'CLM-2026-01184',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_kapoor',
    providerName: 'Priya Kapoor, MD',
    serviceDate: daysAgo(42),
    submittedDate: daysAgo(40),
    processedDate: daysAgo(33),
    status: 'paid',
    serviceType: 'Annual physical',
    diagnosisSummary: 'Routine preventive examination',
    billedAmount: 220,
    allowedAmount: 180,
    planPaid: 155,
    deductibleApplied: 0,
    copayApplied: 25,
    coinsuranceApplied: 0,
    memberResponsibility: 25,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_2',
    claimNumber: 'CLM-2026-01201',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_mila_alvarez',
    patientName: 'Mila Alvarez',
    providerId: 'prov_suarez',
    providerName: 'Elena Suarez, MD',
    serviceDate: daysAgo(38),
    submittedDate: daysAgo(36),
    processedDate: daysAgo(29),
    status: 'paid',
    serviceType: 'Well-child visit',
    diagnosisSummary: 'Routine well-child exam and vaccinations',
    billedAmount: 190,
    allowedAmount: 160,
    planPaid: 160,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 0,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_3',
    claimNumber: 'CLM-2026-01245',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_webb',
    providerName: 'Marcus Webb, MD',
    serviceDate: daysAgo(30),
    submittedDate: daysAgo(28),
    processedDate: daysAgo(21),
    status: 'paid',
    serviceType: 'Cardiology consult',
    diagnosisSummary: 'Evaluation of elevated blood pressure',
    billedAmount: 380,
    allowedAmount: 310,
    planPaid: 0,
    deductibleApplied: 310,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 310,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_4',
    claimNumber: 'CLM-2026-01267',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_rowan_alvarez',
    patientName: 'Rowan Alvarez',
    providerId: 'prov_chen',
    providerName: 'Naomi Chen, MD',
    serviceDate: daysAgo(25),
    submittedDate: daysAgo(24),
    processedDate: daysAgo(17),
    status: 'paid',
    serviceType: 'Annual exam',
    diagnosisSummary: 'Routine preventive well-woman exam',
    billedAmount: 260,
    allowedAmount: 210,
    planPaid: 210,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 0,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_5',
    claimNumber: 'CLM-2026-01402',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_otieno',
    providerName: 'Samuel Otieno, MD',
    serviceDate: daysAgo(6),
    submittedDate: daysAgo(5),
    processedDate: null,
    status: 'in_review',
    serviceType: 'Knee MRI and consult',
    diagnosisSummary: 'Evaluation of right knee pain following a running injury',
    billedAmount: 1450,
    allowedAmount: 0,
    planPaid: 0,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 0,
    denialReason: null,
    eobAvailable: false,
  },
  {
    id: 'clm_6',
    claimNumber: 'CLM-2026-01310',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_whitfield',
    providerName: 'Dana Whitfield, DPT',
    serviceDate: daysAgo(15),
    submittedDate: daysAgo(14),
    processedDate: daysAgo(9),
    status: 'paid',
    serviceType: 'Physical therapy session',
    diagnosisSummary: 'Post-injury rehabilitation, right knee',
    billedAmount: 140,
    allowedAmount: 120,
    planPaid: 80,
    deductibleApplied: 0,
    copayApplied: 40,
    coinsuranceApplied: 0,
    memberResponsibility: 40,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_7',
    claimNumber: 'CLM-2026-01356',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_mila_alvarez',
    patientName: 'Mila Alvarez',
    providerId: 'prov_alvarado',
    providerName: 'Victor Alvarado, MD',
    serviceDate: daysAgo(11),
    submittedDate: daysAgo(11),
    processedDate: daysAgo(6),
    status: 'paid',
    serviceType: 'Urgent care visit — fever',
    diagnosisSummary: 'Acute upper respiratory infection',
    billedAmount: 310,
    allowedAmount: 260,
    planPaid: 185,
    deductibleApplied: 0,
    copayApplied: 75,
    coinsuranceApplied: 0,
    memberResponsibility: 75,
    denialReason: null,
    eobAvailable: true,
  },
  {
    id: 'clm_8',
    claimNumber: 'CLM-2026-01298',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_grant',
    providerName: 'Felicia Grant, MD',
    serviceDate: daysAgo(22),
    submittedDate: daysAgo(20),
    processedDate: daysAgo(13),
    status: 'denied',
    serviceType: 'Skin biopsy',
    diagnosisSummary: 'Evaluation of suspicious skin lesion',
    billedAmount: 540,
    allowedAmount: 0,
    planPaid: 0,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 540,
    denialReason: 'Provider is out-of-network. This plan does not cover out-of-network specialist visits without an approved referral.',
    eobAvailable: true,
  },
  {
    id: 'clm_9',
    claimNumber: 'CLM-2026-01411',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_rowan_alvarez',
    patientName: 'Rowan Alvarez',
    providerId: 'prov_brooks',
    providerName: 'Alan Brooks, MD',
    serviceDate: daysAgo(3),
    submittedDate: daysAgo(2),
    processedDate: null,
    status: 'submitted',
    serviceType: 'Mental health follow-up',
    diagnosisSummary: 'Medication management follow-up',
    billedAmount: 210,
    allowedAmount: 0,
    planPaid: 0,
    deductibleApplied: 0,
    copayApplied: 0,
    coinsuranceApplied: 0,
    memberResponsibility: 0,
    denialReason: null,
    eobAvailable: false,
  },
];

export const seedPriorAuthorizations: PriorAuthorization[] = [
  {
    id: 'pa_1',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_otieno',
    providerName: 'Samuel Otieno, MD',
    serviceRequested: 'Knee MRI (advanced imaging)',
    requestedDate: daysAgo(10),
    decisionDate: daysAgo(7),
    status: 'approved',
    validThrough: daysFromNow(83),
    notes: 'Approved for one MRI of the right knee. Valid for 90 days from decision.',
  },
  {
    id: 'pa_2',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_rowan_alvarez',
    patientName: 'Rowan Alvarez',
    providerId: 'prov_chen',
    providerName: 'Naomi Chen, MD',
    serviceRequested: 'Genetic screening panel',
    requestedDate: daysAgo(3),
    decisionDate: null,
    status: 'pending',
    validThrough: null,
    notes: 'Under clinical review. Decisions are typically issued within 5-7 business days.',
  },
  {
    id: 'pa_3',
    memberId: 'mem_jordan_alvarez',
    patientId: 'mem_jordan_alvarez',
    patientName: 'Jordan Alvarez',
    providerId: 'prov_kim',
    providerName: 'Grace Kim, MD',
    serviceRequested: 'Mole removal procedure (dermatology)',
    requestedDate: daysAgo(20),
    decisionDate: daysAgo(15),
    status: 'denied',
    validThrough: null,
    notes: 'Not medically necessary per clinical review. Member may appeal within 60 days.',
  },
  {
    id: 'pa_4',
    memberId: 'mem_jordan_alvarez',
    patientId: 'dep_mila_alvarez',
    patientName: 'Mila Alvarez',
    providerId: 'prov_suarez',
    providerName: 'Elena Suarez, MD',
    serviceRequested: 'Specialist referral — allergy testing',
    requestedDate: daysAgo(30),
    decisionDate: daysAgo(27),
    status: 'approved',
    validThrough: daysFromNow(33),
    notes: 'Approved referral to an in-network allergist. Valid for 60 days from decision.',
  },
];

export const seedPayments: Payment[] = [
  {
    id: 'pay_apr',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'April 2026 premium',
    amount: 612,
    dueDate: daysAgo(155),
    paidDate: daysAgo(155),
    status: 'paid',
    method: 'Autopay — Visa •••• 4412',
    invoiceNumber: 'INV-2026-0412',
  },
  {
    id: 'pay_may',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'May 2026 premium',
    amount: 612,
    dueDate: daysAgo(124),
    paidDate: daysAgo(124),
    status: 'paid',
    method: 'Autopay — Visa •••• 4412',
    invoiceNumber: 'INV-2026-0512',
  },
  {
    id: 'pay_jun',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'June 2026 premium',
    amount: 612,
    dueDate: daysAgo(93),
    paidDate: daysAgo(93),
    status: 'paid',
    method: 'Autopay — Visa •••• 4412',
    invoiceNumber: 'INV-2026-0612',
  },
  {
    id: 'pay_jul',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'July 2026 premium',
    amount: 612,
    dueDate: daysAgo(62),
    paidDate: daysAgo(60),
    status: 'paid',
    method: 'Manual — Bank transfer',
    invoiceNumber: 'INV-2026-0712',
  },
  {
    id: 'pay_aug',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'August 2026 premium',
    amount: 612,
    dueDate: daysAgo(31),
    paidDate: daysAgo(31),
    status: 'paid',
    method: 'Autopay — Visa •••• 4412',
    invoiceNumber: 'INV-2026-0812',
  },
  {
    id: 'pay_sep',
    memberId: 'mem_jordan_alvarez',
    periodLabel: 'September 2026 premium',
    amount: 612,
    dueDate: daysFromNow(5),
    paidDate: null,
    status: 'scheduled',
    method: 'Autopay — Visa •••• 4412',
    invoiceNumber: 'INV-2026-0912',
  },
];

export const seedDocuments: PortalDocument[] = [
  {
    id: 'doc_plan_document',
    memberId: 'mem_jordan_alvarez',
    category: 'plan_document',
    title: 'Summary of Benefits and Coverage (SBC)',
    date: '2026-01-01T00:00:00.000Z',
    description: 'Full plan document for CarePath Gold PPO, effective January 1, 2026.',
    relatedClaimId: null,
  },
  {
    id: 'doc_id_card',
    memberId: 'mem_jordan_alvarez',
    category: 'id_card',
    title: 'CarePath Member ID Card',
    date: '2026-01-01T00:00:00.000Z',
    description: 'Digital ID card for Jordan Alvarez and covered dependents.',
    relatedClaimId: null,
  },
  {
    id: 'doc_eob_1',
    memberId: 'mem_jordan_alvarez',
    category: 'eob',
    title: 'EOB — Annual physical (Priya Kapoor, MD)',
    date: daysAgo(33),
    description: 'Explanation of benefits for claim CLM-2026-01184.',
    relatedClaimId: 'clm_1',
  },
  {
    id: 'doc_eob_3',
    memberId: 'mem_jordan_alvarez',
    category: 'eob',
    title: 'EOB — Cardiology consult (Marcus Webb, MD)',
    date: daysAgo(21),
    description: 'Explanation of benefits for claim CLM-2026-01245.',
    relatedClaimId: 'clm_3',
  },
  {
    id: 'doc_eob_7',
    memberId: 'mem_jordan_alvarez',
    category: 'eob',
    title: 'EOB — Urgent care visit (Mila Alvarez)',
    date: daysAgo(6),
    description: 'Explanation of benefits for claim CLM-2026-01356.',
    relatedClaimId: 'clm_7',
  },
  {
    id: 'doc_tax_1095b',
    memberId: 'mem_jordan_alvarez',
    category: 'tax_form',
    title: '2025 Form 1095-B',
    date: '2026-01-25T00:00:00.000Z',
    description: 'Health coverage tax form for the 2025 plan year.',
    relatedClaimId: null,
  },
];
